### ISSUE TITLE
help needed with installation & setup

### ISSUE THREAD

**Issue by rafalolszewskii** [maykinmedia/django-regex-redirects#11]
I've installed `django-regex-redirects` via `pip install`, added it to installed apps & added middleware, but it turns out it won't start my app at all now.

Traceback:
```
Unhandled exception in thread started by <function wrapper at 0x7f8aa2af1a28>
Traceback (most recent call last):
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/rafal/dev/projects/myProject/ueFront/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/home/rafal/.virtualenvs/myProject/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by julesallen** [comment]
@rafalolszewskii, if you're swapping out standard django.contrib redirects try loading regex redirects in the same place.

Also if you start a brand new project and only load regex redirects does it still error on your system?
